name: My_First_Action

on:
  push:
    branches: [master]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  First_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  Second_build: 
    runs-on: ubuntu-latest
    needs: [First_build]
    
    steps:
      - name: Print ls-la
        run: ls -la
        
      - name: check Python
        run: python --version
        
      - name: check Apache
        run: appache --version
